name: pr-first-response

on:
  pull_request:
    types: [opened]

jobs: 
  send-response:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch random comment 🗣️
      - name: Add PR comment
        if: "${{ data != '' }}"
        uses: actions/github-script@v5
        with:
          script: |
            const response = await fetch('https://collaboratorsv2.euwest01.umbraco.io/umbraco/api/comments/PostComment', {
              method: 'post',
              body: JSON.stringify({
                repo: '${{ github.repository }}',
                number: '${{ github.event.number }}',
                actor: '${{ github.actor }}',
                commentType: 'opened-pr-first-comment'
              }),
              headers: {
                'Authorization': 'Bearer ${{ secrets.OUR_BOT_API_TOKEN }}'
                'Content-Type': 'application/json'
              }
            });
            
            const data = await response.text();

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: data
            });