name: pr-first-response
on: [pull_request]

jobs: 
  send-response:
  
    runs-on: ubuntu-latest
    steps:
      - name: Fetch random comment 🗣️
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          ENDPOINT: https://envwtw2mocrhl.x.pipedream.net/
          CONFIGURATION: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.OUR_BOT_API_TOKEN }}"} }'