name: pr-first-response

on:
  pull_request:
    types: [opened]

jobs: 
  send-response:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch random comment 🗣️
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          ENDPOINT: https://webhook.site/00f723b3-783e-42c7-a422-50662a9a94dd
          CONFIGURATION: '{ "method": "POST", "headers": {"Authorization": "Bearer ${{ secrets.OUR_BOT_API_TOKEN }}"}, "body": { "repo": "${{ github.repository }}", "number": "${{ github.event.number }}", "actor": "${{ github.actor }}, "commentType": \"opened-pr-first-comment\""} }'
      - name: Add PR comment
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ fromJson(env.fetch-api-data).hello }}`
            })